# Notices:
# - If you want to change the secret field, replace the '<no-change>' placeholder to '<user-input>' in this file, the application will prompt you to enter a value when it runs.
# - Manually save the file will create the connection after basic validation.
# - The connection information will be stored in a local database with api_key encrypted for safety.
# - Prompt flow will ONLY use the connection information (incl. keys) when instructed by you, e.g. manage connections, use connections to run flow etc.
# - All the values should be string type, please use "123" instead of 123 or "True" instead of True.

# - You have several ways to get such info:
#   1. Go to the AOAI studio, open playground, view code, then you can get what you need;
#   2. Go to the AOAI studio, settings -- resource -- list of resource, endpoint is api_base and key is api_key;
#   3. Go to the Azure portal, find your AOAI resource, and then get the keys.

$schema: https://azuremlschemas.azureedge.net/promptflow/latest/AzureOpenAIConnection.schema.json
name: "lioropenaitest"
type: azure_open_ai # snake case
api_key: "<no-change>" # Use'<no-change>' to keep original value or '<user-input>' to update it when the application runs.
api_base: "https://gbbailiortestopenai1.openai.azure.com"
api_type: "azure"
api_version: "2024-02-15-preview"