$schema: 
  https://azuremlschemas.azureedge.net/promptflow/latest/AzureOpenAIConnection.schema.json
type: azure_open_ai
name: lioropenaitest
module: promptflow.connections
api_base: https://gbbailiortestopenai1.openai.azure.com
api_key: ${env:LIOROPENAITEST_API_KEY}
api_type: azure
api_version: 2024-02-15-preview
auth_mode: key
